name: Auto Request Reviewers

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  request_review:
    runs-on: ubuntu-latest
    steps:
    - name: Request Reviewers
      uses: actions/github-script@v6
      with:
        script: |
          (async () => {
            const { context, getOctokit } = require('@actions/github');
            const token = process.env.GITHUB_TOKEN;
            const octokit = getOctokit(token);

            const reviewers = ['kkraman02', 'username2'];
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;

            await octokit.rest.pulls.requestReviewers({
              owner,
              repo,
              pull_number,
              reviewers
            });
          })();
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
